-- Desativa o modo de segurança para permitir apagar todos os produtos
SET SQL_SAFE_UPDATES = 0;

-- Limpa a tabela de produtos antes de inserir os novos para evitar duplicatas
DELETE FROM products;

-- Reseta o contador do ID para começar do 1 novamente
ALTER TABLE products AUTO_INCREMENT = 1;

-- Insere todos os seus produtos
INSERT INTO products (name, price, category, description, image, available) VALUES
-- Esfirras Salgadas
('Carne', 4.50, 'Esfirras Salgadas', 'Carne moída, tomate, cebola e temperos especiais.', 'assets/esfirra-carne.png', true),
('Carne I', 6.50, 'Esfirras Salgadas', 'Carne com catupiry.', 'assets/esfirra-carne-catupiry.png', true),
('Carne II', 7.00, 'Esfirras Salgadas', 'Carne com queijo muçarela.', 'assets/esfirra-carne-mucarela.png', true),
('Calabresa', 4.50, 'Esfirras Salgadas', 'Calabresa.', 'assets/esfirra-calabresa.png', true),
('Calabresa I', 6.50, 'Esfirras Salgadas', 'Calabresa com catupiry.', 'assets/esfirra-calabresa-catupiry.png', true),
('Calabresa II', 7.00, 'Esfirras Salgadas', 'Calabresa com queijo muçarela.', 'assets/esfirra-calabresa-mucarela.png', true),
('Frango', 5.00, 'Esfirras Salgadas', 'Frango desfiado.', 'assets/esfirra-frango.png', true),
('Frango I', 6.50, 'Esfirras Salgadas', 'Frango com catupiry.', 'assets/esfirra-frango-catupiry.png', true),
('Frango II', 7.00, 'Esfirras Salgadas', 'Frango com queijo muçarela.', 'assets/esfirra-frango-mucarela.png', true),
('Frango, Queijo e Bacon', 8.00, 'Esfirras Salgadas', 'Frango, queijo e bacon.', 'assets/esfirra-frango-queijo-bacon.png', true),
('Frango c/ Milho', 7.00, 'Esfirras Salgadas', 'Frango com creme de milho.', 'assets/esfirra-frango-creme-milho.png', true),
('Frango c/ Milho I', 7.50, 'Esfirras Salgadas', 'Frango com creme de milho e catupiry.', 'assets/esfirra-frango-milho-catupiry.png', true),
('Frango c/ Milho II', 8.00, 'Esfirras Salgadas', 'Frango com creme de milho e muçarela.', 'assets/esfirra-frango-milho-mucarela.png', true),
('Palmito', 5.00, 'Esfirras Salgadas', 'Palmito.', 'assets/esfirra-palmito.png', true),
('Palmito I', 7.00, 'Esfirras Salgadas', 'Palmito com catupiry.', 'assets/esfirra-palmito-catupiry.png', true),
('Palmito II', 7.50, 'Esfirras Salgadas', 'Palmito com queijo muçarela.', 'assets/esfirra-palmito-mucarela.png', true),
('Milho', 5.00, 'Esfirras Salgadas', 'Milho.', 'assets/esfirra-milho.png', true),
('Milho I', 7.00, 'Esfirras Salgadas', 'Milho com catupiry.', 'assets/esfirra-milho-catupiry.png', true),
('Milho II', 7.50, 'Esfirras Salgadas', 'Milho com queijo muçarela.', 'assets/esfirra-milho-mucarela.png', true),
('Atum', 7.50, 'Esfirras Salgadas', 'Atum.', 'assets/esfirra-atum.png', true),
('Atum I', 8.50, 'Esfirras Salgadas', 'Atum com catupiry.', 'assets/esfirra-atum-catupiry.png', true),
('Atum II', 9.50, 'Esfirras Salgadas', 'Atum com queijo muçarela.', 'assets/esfirra-atum-mucarela.png', true),
('Escarola', 7.50, 'Esfirras Salgadas', 'Escarola com bacon.', 'assets/esfirra-escarola-bacon.png', true),
('Escarola I', 8.50, 'Esfirras Salgadas', 'Escarola com bacon e catupiry.', 'assets/esfirra-escarola-bacon-catupiry.png', true),
('Escarola II', 8.50, 'Esfirras Salgadas', 'Escarola com bacon e queijo muçarela.', 'assets/esfirra-escarola-bacon-mucarela.png', true),
('Pizza', 8.50, 'Esfirras Salgadas', 'Molho de tomate, queijo muçarela, orégano, tomate e cebola.', 'assets/esfirra-pizza.png', true),
('Picante', 8.50, 'Esfirras Salgadas', 'Queijo muçarela, calabresa, cebola e pimenta.', 'assets/esfirra-picante.png', true),
('Queijo', 6.00, 'Esfirras Salgadas', 'Queijo muçarela.', 'assets/esfirra-queijo.png', true),
('Dois Queijos', 6.50, 'Esfirras Salgadas', 'Queijo muçarela e catupiry.', 'assets/esfirra-dois-queijos.png', true),
('Três Queijos', 8.00, 'Esfirras Salgadas', 'Queijo muçarela, provolone e catupiry.', 'assets/esfirra-tres-queijos.png', true),
('Quatro Queijos', 9.00, 'Esfirras Salgadas', 'Queijo muçarela, provolone, parmesão e catupiry.', 'assets/esfirra-quatro-queijos.png', true),
('Catupiry', 7.50, 'Esfirras Salgadas', 'Requeijão catupiry.', 'assets/esfirra-catupiry.png', true),
('Catupiry c/ Bacon', 8.00, 'Esfirras Salgadas', 'Catupiry com bacon.', 'assets/esfirra-catupiry-bacon.png', true),
('Quatro Queijos c/ Bacon', 9.50, 'Esfirras Salgadas', 'Queijo muçarela, provolone, parmesão, catupiry e bacon.', 'assets/esfirra-quatro-queijos-bacon.png', true),
('Queijo c/ Bacon', 7.50, 'Esfirras Salgadas', 'Queijo muçarela com bacon.', 'assets/esfirra-queijo-bacon.png', true),
('Queijo c/ Bacon I', 9.00, 'Esfirras Salgadas', 'Queijo, bacon e catupiry.', 'assets/esfirra-queijo-bacon-catupiry.png', true),
('Quatro Queijos c/ Alho', 9.50, 'Esfirras Salgadas', 'Muçarela, provolone, parmesão, catupiry e alho.', 'assets/esfirra-quatro-queijos-alho.png', true),
('Alho', 7.00, 'Esfirras Salgadas', 'Queijo muçarela com alho.', 'assets/esfirra-alho.png', true),
('Camarão', 9.00, 'Esfirras Salgadas', 'Camarão com creme.', 'assets/esfirra-camarao.png', true),
('Camarão I', 10.00, 'Esfirras Salgadas', 'Camarão com creme e catupiry.', 'assets/esfirra-camarao-catupiry.png', true),
('Camarão II', 11.00, 'Esfirras Salgadas', 'Camarão com creme e muçarela.', 'assets/esfirra-camarao-mucarela.png', true),
('Brócolis c/ Bacon', 7.50, 'Esfirras Salgadas', 'Brócolis com bacon.', 'assets/esfirra-brocolis-bacon.png', true),
('Brócolis I', 8.50, 'Esfirras Salgadas', 'Brócolis, bacon e catupiry.', 'assets/esfirra-brocolis-bacon-catupiry.png', true),
('Brócolis II', 9.00, 'Esfirras Salgadas', 'Brócolis, bacon e queijo.', 'assets/esfirra-brocolis-bacon-queijo.png', true),
('Lombinho I', 8.50, 'Esfirras Salgadas', 'Lombo, creme de leite, catupiry, tomate, cebola e orégano.', 'assets/esfirra-lombinho-1.png', true),
('Lombinho II', 9.00, 'Esfirras Salgadas', 'Lombo, queijo, creme de leite, catupiry, tomate, cebola e orégano.', 'assets/esfirra-lombinho-2.png', true),
('Estrogonofe', 8.50, 'Esfirras Salgadas', 'Estrogonofe de frango, batata palha.', 'assets/esfirra-estrogonofe.png', true),
('Presunto', 8.50, 'Esfirras Salgadas', 'Presunto, queijo, orégano.', 'assets/esfirra-presunto.png', true),
('Coalhada', 9.50, 'Esfirras Salgadas', 'Coalhada, azeite, gergelim e limão.', 'assets/esfirra-coalhada.png', true),
('Rúcula c/ Tomate Seco', 10.00, 'Esfirras Salgadas', 'Tomate seco, creme de leite e muçarela.', 'assets/esfirra-rucula-tomate-seco.png', true),
('Marguerita', 9.00, 'Esfirras Salgadas', 'Queijo, tomate, azeite e manjericão.', 'assets/esfirra-marguerita.png', true),
('Costela', 9.50, 'Esfirras Salgadas', 'Costela bovina, queijo, tomate, cebola e barbecue.', 'assets/esfirra-costela.png', true),
('Chocolate Preto', 7.50, 'Esfirras Doces', 'Esfirra doce com recheio de chocolate preto.', 'assets/esfirra-chocolate-preto.png', true),
('Chocolate Branco', 8.50, 'Esfirras Doces', 'Esfirra doce com recheio de chocolate branco.', 'assets/esfirra-chocolate-branco.png', true),
('Chocolate Preto c/ Morango', 8.50, 'Esfirras Doces', 'Esfirra de chocolate preto com morangos.', 'assets/esfirra-chocolate-preto-morango.png', true),
('Chocolate Branco c/ Morango', 8.50, 'Esfirras Doces', 'Esfirra de chocolate branco com morangos.', 'assets/esfirra-chocolate-branco-morango.png', true),
('Chocolate Preto c/ Banana', 8.50, 'Esfirras Doces', 'Esfirra de chocolate preto com banana.', 'assets/esfirra-chocolate-preto-banana.png', true),
('Chocolate Branco c/ Banana', 8.50, 'Esfirras Doces', 'Esfirra de chocolate branco com banana.', 'assets/esfirra-chocolate-branco-banana.png', true),
('Ioio Cream', 8.50, 'Esfirras Doces', 'Chocolate preto e branco.', 'assets/esfirra-ioio-cream.png', true),
('Ioio Cream I', 8.80, 'Esfirras Doces', 'Chocolate preto e branco com morango.', 'assets/esfirra-ioio-cream-morango.png', true),
('Ioio Cream II', 8.50, 'Esfirras Doces', 'Chocolate preto e branco com banana.', 'assets/esfirra-ioio-cream-banana.png', true),
('Banana', 8.00, 'Esfirras Doces', 'Queijo muçarela, leite condensado, banana e canela.', 'assets/esfirra-banana.png', true),
('Prestígio', 8.50, 'Esfirras Doces', 'Chocolate com coco.', 'assets/esfirra-prestigio.png', true),
('Brigadeiro', 8.50, 'Esfirras Doces', 'Chocolate preto com granulado.', 'assets/esfirra-brigadeiro.png', true),
('Romeu e Julieta', 8.50, 'Esfirras Doces', 'Muçarela com goiabada.', 'assets/esfirra-romeu-julieta.png', true),
('Chocolate Preto c/ Pimenta', 8.50, 'Esfirras Doces', 'Chocolate preto com pimenta.', 'assets/esfirra-chocolate-preto-pimenta.png', true),
('Chocolate Branco c/ Pimenta', 8.50, 'Esfirras Doces', 'Chocolate branco com pimenta.', 'assets/esfirra-chocolate-branco-pimenta.png', true),
('Confetti', 9.50, 'Esfirras Doces', 'Chocolate preto com confetti.', 'assets/esfirra-confetti.png', true),
('Nutella c/ Ninho', 9.50, 'Esfirras Doces', 'Nutella (creme de avelã) com leite ninho em pó.', 'assets/esfirra-nutella-ninho.png', true),
('Nutella c/ Confetti', 9.50, 'Esfirras Doces', 'Nutella (creme de avelã) com confetti.', 'assets/esfirra-nutella-confetti.png', true),
('Ninho', 8.50, 'Esfirras Doces', 'Creme de leite ninho.', 'assets/esfirra-ninho.png', true),
('Nevada de Banana', 10.00, 'Esfirras Doces', 'Queijo muçarela, leite condensado, banana, canela e chocolate branco granulado.', 'assets/esfirra-nevada-banana.png', true),
('Nevada de Maracujá', 10.00, 'Esfirras Doces', 'Leite condensado, queijo, maracujá e chocolate branco.', 'assets/esfirra-nevada-maracuja.png', true),
('Doce de Leite', 8.50, 'Esfirras Doces', 'Doce de leite e muçarela.', 'assets/esfirra-doce-de-leite.png', true),
('Cookies', 9.00, 'Esfirras Doces', 'Esfirra sabor cookies.', 'assets/esfirra-cookies.png', true),
('Amendoim', 9.50, 'Esfirras Doces', 'Creme de amendoim.', 'assets/esfirra-amendoim.png', true),
('Shawarma Filé', 19.00, 'Shawarma', 'Churrasco de filé, rúcula, vinagrete, batata palha, creme de alho da casa. Opção com pimenta.', 'assets/shawarma-file.png', true),
('Shawarma Frango', 19.00, 'Shawarma', 'Churrasco de frango, rúcula, vinagrete, batata palha, creme de alho da casa. Opção com pimenta.', 'assets/shawarma-frango.png', true),
('Kibe Carne', 8.00, 'Kibes', 'Kibe com carne.', 'assets/kibe-carne.png', true),
('Kibe I', 8.00, 'Kibes', 'Kibe com catupiry.', 'assets/kibe-catupiry.png', true),
('Kibe II', 9.00, 'Kibes', 'Kibe com queijo muçarela.', 'assets/kibe-mucarela.png', true),
('Kibe Cru', 17.00, 'Kibes', 'Kibe cru.', 'assets/kibe-cru.png', true),
('Kibe Cru c/ Coalhada Seca', 25.00, 'Kibes', 'Kibe cru acompanhado de coalhada seca.', 'assets/kibe-cru-coalhada.png', true),
('Kibe Assado I', 20.00, 'Kibes', 'Kibe assado com catupiry.', 'assets/kibe-assado-catupiry.png', true),
('Kibe Assado II', 22.00, 'Kibes', 'Kibe assado com queijo.', 'assets/kibe-assado-queijo.png', true),
('Kibe Assado III', 21.00, 'Kibes', 'Kibe assado com queijo, tomate e cebola.', 'assets/kibe-assado-completo.png', true),
('Kibe Assado Completo c/ Coalhada Seca', 25.00, 'Kibes', 'Kibe assado completo com coalhada seca.', 'assets/kibe-assado-completo-coalhada.png', true),
('Mini Kibe', 25.00, 'Kibes', 'Porção com 12 unidades.', 'assets/mini-kibe.png', true),
('Kafta', 15.00, 'Kibes', 'Espeto de Kafta.', 'assets/kafta.png', true),
('Beirute de Frango', 28.00, 'Beirutes', 'Frango, presunto, muçarela, bacon, ovo, catupiry, queijo cheddar, maionese, alface, tomate.', 'assets/beirute-frango.png', true),
('Beirute de Filé', 29.00, 'Beirutes', 'Filé, presunto, muçarela, bacon, ovo, catupiry, cheddar, maionese, alface e tomate.', 'assets/beirute-file.png', true),
('Beirute Carne Louca', 29.00, 'Beirutes', 'Carne louca, presunto, muçarela, catupiry, queijo cheddar, maionese, alface, tomate.', 'assets/beirute-carne-louca.png', true),
('Beirute de Linguiça', 28.00, 'Beirutes', 'Linguiça, presunto, muçarela, catupiry, rúcula e maionese.', 'assets/beirute-linguica.png', true),
('Beirute de Kafta', 28.00, 'Beirutes', 'Presunto, muçarela, catupiry, maionese, alface ou rúcula e tomate.', 'assets/beirute-kafta.png', true),
('Bauru de Costela', 26.00, 'Lanches', 'Queijo, tomate, costela desfiada, vinagrete e barbecue.', 'assets/bauru-costela.png', true),
('Bauru de Pernil', 25.00, 'Lanches', 'Queijo, tomate, pernil desfiado, vinagrete e barbecue.', 'assets/bauru-pernil.png', true),
('Bauru de Filé Mignon', 37.00, 'Lanches', 'Filé mignon, tomate, alface, rúcula, cebola e maionese, muçarela.', 'assets/bauru-file-mignon.png', true),
('Bauru de Contra Filé', 28.00, 'Lanches', 'Contra filé, tomate, cebola, maionese, muçarela.', 'assets/bauru-contra-file.png', true),
('Bauru de Picanha', 36.00, 'Lanches', 'Filé picanha, tomate, cebola, alface, maionese, muçarela.', 'assets/bauru-picanha.png', true),
('Bauru de Tilápia', 34.00, 'Lanches', 'Filé de tilápia empanado, molho de tomate, maionese, alface, tomate, cebola e muçarela.', 'assets/bauru-tilapia.png', true),
('Bauru de Linguiça', 27.00, 'Lanches', 'Linguiça, tomate, maionese, alface, tomate, rúcula, muçarela.', 'assets/bauru-linguica.png', true),
('Bauru de Frango', 27.00, 'Lanches', 'Filé de frango, tomate, cebola, maionese, muçarela.', 'assets/bauru-frango.png', true),
('Zap Burguer', 22.00, 'Lanches', 'Hambúrguer, alface, catupiry, queijo cheddar, cebola e molho especial.', 'assets/zap-burguer.png', true),
('Zap Burguer Frango', 22.00, 'Lanches', 'Hambúrguer de frango, alface, catupiry, queijo cheddar, cebola e molho especial.', 'assets/zap-burguer-frango.png', true),
('Zap Burguer Duplo', 28.00, 'Lanches', 'Dois hambúrgueres filé, alface, catupiry, queijo cheddar, cebola e molho especial.', 'assets/zap-burguer-duplo.png', true),
('Zap Burguer Duplo Frango', 28.00, 'Lanches', 'Dois hambúrgueres de frango, alface, catupiry, queijo cheddar, cebola e molho especial.', 'assets/zap-burguer-duplo-frango.png', true),
('Zap Artesanal de Carne', 31.00, 'Lanches', 'Carne, bacon, cebola, catupiry, cheddar, molho especial.', 'assets/zap-artesanal-carne.png', true),
('Mini Pastel (12 unidades)', 33.00, 'Pastéis', 'Carne, calabresa, frango e queijo.', 'assets/mini-pastel.png', true),
('Pastel Tradicional', 12.50, 'Pastéis', 'Carne, calabresa, frango ou queijo.', 'assets/pastel-tradicional.png', true),
('Pastel Tradicional Doce', 15.00, 'Pastéis Doces', 'Chocolate branco, chocolate preto.', 'assets/pastel-tradicional-doce.png', true),
('Porção de Carne (400g)', 65.00, 'Porções', 'Carne bovina, batata frita, cebola.', 'assets/porcao-carne.png', true),
('Porção Tirinhas de Peixe (400mg)', 61.00, 'Porções', 'Tiras de peixe empanadas.', 'assets/porcao-tirinhas-peixe.png', true),
('Porção de Frango (400g)', 57.00, 'Porções', 'Frango, batata frita, cebola.', 'assets/porcao-frango.png', true),
('Porção de Calabresa (400g)', 52.00, 'Porções', 'Calabresa, batata frita, cebola.', 'assets/porcao-calabresa.png', true),
('Espeto de Frango', 25.00, 'Porções', 'Espeto de frango empanado.', 'assets/espeto-frango.png', true),
('Mini Chicken (400g)', 25.00, 'Porções', 'Porção de mini chicken.', 'assets/mini-chicken.png', true),
('Frango a Passarinho (500g)', 31.00, 'Porções', 'Porção de frango a passarinho.', 'assets/frango-a-passarinho.png', true),
('Batata Frita (400g)', 21.00, 'Batatas Porções', 'Porção de batata frita.', 'assets/batata-frita.png', true),
('Batata c/ Catupiry (400g)', 22.00, 'Batatas Porções', 'Porção de batata frita com catupiry.', 'assets/batata-catupiry.png', true),
('Batata c/ Queijo (400g)', 22.00, 'Batatas Porções', 'Porção de batata frita com queijo.', 'assets/batata-queijo.png', true),
('Batata c/ Queijo, Bacon e Catupiry (400g)', 25.00, 'Batatas Porções', 'Porção de batata frita com queijo, bacon e catupiry.', 'assets/batata-queijo-bacon-catupiry.png', true),
('Laranja (copo)', 10.00, 'Sucos', 'Copo de suco de laranja.', 'assets/suco-laranja-copo.png', true),
('Laranja (jarra)', 25.00, 'Sucos', 'Jarra de suco de laranja.', 'assets/suco-laranja-jarra.png', true),
('Laranja c/ Acerola (copo)', 10.00, 'Sucos', 'Copo de suco de laranja com acerola.', 'assets/suco-laranja-acerola-copo.png', true),
('Laranja c/ Acerola (jarra)', 25.00, 'Sucos', 'Jarra de suco de laranja com acerola.', 'assets/suco-laranja-acerola-jarra.png', true),
('Abacaxi (copo)', 10.00, 'Sucos', 'Copo de suco de abacaxi.', 'assets/suco-abacaxi-copo.png', true),
('Abacaxi c/ Hortelã (jarra)', 25.00, 'Sucos', 'Jarra de suco de abacaxi com hortelã.', 'assets/suco-abacaxi-hortela-jarra.png', true),
('Limonada Suíça (copo)', 10.00, 'Sucos', 'Copo de limonada suíça.', 'assets/suco-limonada-copo.png', true),
('Limonada Suíça (jarra)', 25.00, 'Sucos', 'Jarra de limonada suíça.', 'assets/suco-limonada-jarra.png', true),
('Cajú (copo)', 10.00, 'Sucos', 'Copo de suco de cajú.', 'assets/suco-caju-copo.png', true),
('Cajú (jarra)', 25.00, 'Sucos', 'Jarra de suco de cajú.', 'assets/suco-caju-jarra.png', true),
('Morango (copo)', 10.00, 'Sucos', 'Copo de suco de morango.', 'assets/suco-morango-copo.png', true),
('Morango (jarra)', 25.00, 'Sucos', 'Jarra de suco de morango.', 'assets/suco-morango-jarra.png', true),
('Maracujá (copo)', 10.00, 'Sucos', 'Copo de suco de maracujá.', 'assets/suco-maracuja-copo.png', true),
('Maracujá (jarra)', 25.00, 'Sucos', 'Jarra de suco de maracujá.', 'assets/suco-maracuja-jarra.png', true),
('Uva (copo)', 10.00, 'Sucos', 'Copo de suco de uva.', 'assets/suco-uva-copo.png', true),
('Uva (jarra)', 25.00, 'Sucos', 'Jarra de suco de uva.', 'assets/suco-uva-jarra.png', true),
('Caipirinha de Abacaxi', 20.00, 'Caipirinhas', 'Pinga, vodka ou saquê.', 'assets/caipirinha-abacaxi.png', true),
('Caipirinha de Limão', 20.00, 'Caipirinhas', 'Pinga, vodka ou saquê.', 'assets/caipirinha-limao.png', true),
('Caipirinha de Morango', 20.00, 'Caipirinhas', 'Pinga, vodka ou saquê.', 'assets/caipirinha-morango.png', true),
('Caipirinha de Maracujá', 20.00, 'Caipirinhas', 'Pinga, vodka ou saquê.', 'assets/caipirinha-maracuja.png', true),
('Chope Caneca', 10.00, 'Chope/Cervejas', 'Caneca de chope.', 'assets/chope-caneca.png', true),
('Chope Tulipa', 8.00, 'Chope/Cervejas', 'Tulipa de chope.', 'assets/chope-tulipa.png', true),
('Chope Escuro Tulipa', 9.00, 'Chope/Cervejas', 'Tulipa de chope escuro.', 'assets/chope-escuro-tulipa.png', true),
('Chope c/ Menta Tulipa', 9.00, 'Chope/Cervejas', 'Tulipa de chope com menta.', 'assets/chope-menta-tulipa.png', true),
('Chope c/ Groselha Tulipa', 9.00, 'Chope/Cervejas', 'Tulipa de chope com groselha.', 'assets/chope-groselha-tulipa.png', true),
('Chope Menta ou Groselha (caneca 400ml)', 12.00, 'Chope/Cervejas', 'Caneca de 400ml de chope com menta ou groselha.', 'assets/chope-menta-groselha-caneca.png', true),
('Cerveja Lata', 7.00, 'Chope/Cervejas', 'Lata de cerveja.', 'assets/cerveja-lata.png', true),
('Cerveja 600 ML', 13.00, 'Chope/Cervejas', 'Garrafa de cerveja 600ml.', 'assets/cerveja-600ml.png', true),
('Heineken 600 ML', 16.50, 'Chope/Cervejas', 'Garrafa de Heineken 600ml.', 'assets/heineken-600ml.png', true),
('Original 600 ML', 14.00, 'Chope/Cervejas', 'Garrafa de Original 600ml.', 'assets/original-600ml.png', true),
('Torre de Chope 2,5 Litros', 49.90, 'Torres', 'Torre de chope com 2,5 litros.', 'assets/torre-chope-2-5l.png', true),
('Torre de Chope 3,5 Litros', 79.90, 'Torres', 'Torre de chope com 3,5 litros.', 'assets/torre-chope-3-5l.png', true),
('Combo Torre Chope 2,5L c/ Carne', 88.00, 'Torres', 'Torre de chope 2,5L com porção de carne, cebola e batata 500g.', 'assets/combo-torre-carne.png', true),
('Combo Torre Chope 2,5L c/ 12 Mini Kibes', 68.00, 'Torres', 'Torre de chope 2,5L com 12 unidades de mini kibes.', 'assets/combo-torre-kibes.png', true),
('Combo Torre Chope 2,5L c/ 12 Mini Pastel', 79.00, 'Torres', 'Torre de chope 2,5L com 12 unidades de mini pastel.', 'assets/combo-torre-pastel.png', true),
('Combo Torre Chope 2,5L c/ 500g Isca de Tilápia', 79.00, 'Torres', 'Torre de chope 2,5L com 500g de isca de tilápia.', 'assets/combo-torre-tilapia.png', true),
('Torre Coca-Cola 2,5L', 26.00, 'Torres', 'Torre de Coca-Cola com 2,5 litros.', 'assets/torre-coca-2-5l.png', true),
('Torre Coca-Cola 2L', 20.00, 'Torres', 'Torre de Coca-Cola com 2 litros.', 'assets/torre-coca-2l.png', true),
('Vinho (taça)', 12.50, 'Vinhos', 'Taça de vinho.', 'assets/vinho-taca.png', true),
('Vinho (garrafa)', 38.00, 'Vinhos', 'Garrafa de vinho.', 'assets/vinho-garrafa.png', true),
('Refrigerante Lata', 7.00, 'Refrigerantes', 'Lata de refrigerante 350ml.', 'assets/refrigerante-lata.png', true),
('Limoneto', 5.00, 'Refrigerantes', 'Garrafa de Limoneto.', 'assets/limoneto.png', true),
('H2O Limão', 9.00, 'Refrigerantes', 'Garrafa de H2O Limão.', 'assets/h2o-limao.png', true),
('Água Mineral', 3.50, 'Refrigerantes', 'Garrafa de água mineral sem gás.', 'assets/agua-mineral.png', true),
('Água com Gás', 4.50, 'Refrigerantes', 'Garrafa de água mineral com gás.', 'assets/agua-com-gas.png', true),
('Petit Gateau c/ Sorvete', 25.00, 'Sobremesas', 'Petit gateau de chocolate com sorvete.', 'assets/petit-gateau.png', true);